lab3-csa:
  stage: test
  image: python:3.10
  script:
    - pip install coverage
    - coverage run -m pytest --verbose
    - find . -type f -name "*.py" | xargs -t coverage report
    # - pip install pycodestyle