name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
        # pip install pycodestyle pylint # Отключено на этапе настройки

    - name: Run tests with coverage
      run: |
        coverage run -m pytest --verbose --update-goldens
        coverage report